- name: curl composer
  command: curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php

- name: install and setup composer
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer


- name: make composer executable
  command: chmod +x /usr/local/bin/composer 

- name: install composer
  command: composer install --no-interaction 
  args:
    chdir: /var/www/altschool/laravel

- name: install composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: 0755

- name: run php artisan commands
  command: php artisan {{ item }}
  args:
    chdir: /var/www/altschool/laravel
  with_items:
    - key:generate
    - config:cache
    - migrate:fresh
    - migrate --seed






   
    